using System.Collections.Generic;
using UnityEngine;
using Mirror;

// IN THIS SCRIPT: Use this script to Add a specific or random item to the Inventory
// WARNING: This script uses UNITY Editor to simplify the process of setting it up
// USE THIS SCRIPT by attaching it next to the script that calls the AddItem() and set up what you want to Add to the inventory in the Editor

public class AddItemToInventory : NetworkBehaviour
{
    // The one bool you set up true is the type of AddItem you want to use
    // The specificItemGive let's you set up a specific Item and quantity to add to the Inventory
    // The randomItemGive let's you choose from a range of items to randomly add to the Inventory
    public bool specificItemGive, randomItemGive;

    // In case of random, this list becomes active in the Editor
    public List<Item> itemsToGive = new List<Item>();

    // In case of specific, this two parameters become active in the Editor
    public Item specificItem;
    public int specificQuant;

    public int RandomNumberForItemLoot; // This number determines what item out of a pool of x items will be found by the player
   public void NumberGenSettingWhatItemDrops()
   {
        RandomNumberForItemLoot = Random.Range(0,6); // Assign a randomly generated item number to a base int
        TellOthersAboutItemNumber(RandomNumberForItemLoot); // Execute the RPC telling other players what item is generated from the item pool. 
                                                            // Thanks to this, they will also get the same item in their inventory.
   }
   [ClientRpc]
   public void TellOthersAboutItemNumber(int NewRandomNumberForItemLoot)
   {
        RandomNumberForItemLoot = NewRandomNumberForItemLoot; // Replace the old intiger with a newly generated one
   }


    // AddItem() is currenlty called by a UI button but you can call it from other script in the same GameObject by using:
    // GetComponent<AddItemToInventory>().AddItem();
    // Don't forget to set up the item you want to give in the Editor
    public void AddItem()
    {
        if(specificItemGive && randomItemGive == false)
        {
            AddSpecificItem();
        }else
       if (specificItemGive == false && randomItemGive)
        {
            AddRandom();
        }

    }
    
    // Adds the specific item and quantity you set up in the Editor to the Inventory
   void AddSpecificItem()
    {
        Inventory.instance.AddItem(specificItem, specificQuant);
    }

    // Adds one random Item from the pre selected list to the Inventory
    void AddRandom()
    {                                                   
        Inventory.instance.AddItem(itemsToGive[RandomNumberForItemLoot], 1); // When adding an item to the inventory -> 
                                                                             // check if the item is specific or random, give the item generated by the method,
                                                                             // specify quantity (in this case 1)
    }

}
